### ISSUE TITLE
FFMPEG HELP?

### ISSUE THREAD

**Issue by AlexNikMak** [cwilby/nextcloud-workflow-media-converter#398]
Hello everyone (I am new to nextcloud and docker)

I have successfully set up nextcloud using docker compose and all working fine.
But I decided to install [nextcloud-workflow-media-converter] and first requirement is to install ffmpeg. But how should I install it?
Should I add it to nextcloud mastercontainer yml file ffmpeg image? Or does nextcloud have console? I am lost, I would appreciate any help.

**Comment by cwilby** [comment]
Hey @AlexNikMak - here are some snippets that should point you in the right direction:

`docker-compose.yml`
```
version: "3.7"

services:
    nextcloud:
        build: .
        ...(etc)
```

`Dockerfile`

```
FROM nextcloud:latest

RUN apt-get update && apt-get install ffmpeg -y
```

In short, add a file called `Dockerfile` next to `docker-compose.yml`. 

The docker compose service should then reference that with `build: .`, instead of `image: nextcloud:latest` as is likely there now.

Hope this helps!
